### ISSUE TITLE
`runOutput` on TestingEmbulk occurs ClassCastException

### ISSUE THREAD

**Issue by joker1007** [embulk/embulk#1220] opened 2020-02-14 16:30 UTC
Issue Type: Bug Report
-----------------------

* OS version: Linux Kernel-4.19.44-gentoo
* Java version: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
  * Embulk version: 0.9.22
  * Your Embulk configuration
```yaml
type: kafka
topic: "json-topic"
serialize_format: json
brokers:
  - "localhost:9092"
```
  *  joker1007/embulk-output-kafka@4cd289e (and write below code)

I executed a below code for testing.

```java
package org.embulk.output.kafka;

import com.google.common.io.Resources;
import org.embulk.config.ConfigSource;
import org.embulk.spi.OutputPlugin;
import org.embulk.test.TestingEmbulk;
import org.junit.Rule;
import org.junit.Test;

import java.io.IOException;
import java.nio.file.Paths;

public class TestKafkaOutputPlugin
{
    @Rule
    public TestingEmbulk embulk = TestingEmbulk.builder()
            .registerPlugin(OutputPlugin.class, "kafka", KafkaOutputPlugin.class)
            .build();

    @Test
    public void testSimpleJson() throws IOException
    {
        ConfigSource configSource = embulk.loadYamlResource("config_simple.yml");
        embulk.runOutput(configSource, Paths.get(Resources.getResource("in1.csv").getPath()));
    }
}
```

I expected TestingEmbulk runs successfully.
But, TestingEmbulk occured ClassCastException.

## Details of the error
```
java.lang.ClassCastException: java.lang.String cannot be cast to org.embulk.standards.CsvParserPlugin$QuoteCharacter
org.embulk.exec.PartialExecutionException: java.lang.ClassCastException: java.lang.String cannot be cast to org.embulk.standards.CsvParserPlugin$QuoteCharacter
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
	at org.embulk.test.TestingEmbulk$OutputBuilder.run(TestingEmbulk.java:448)
	at org.embulk.test.TestingEmbulk.runOutput(TestingEmbulk.java:574)
	at org.embulk.output.kafka.TestKafkaOutputPlugin.testSimpleJson(TestKafkaOutputPlugin.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.embulk.standards.CsvParserPlugin$QuoteCharacter
	at org.embulk.standards.CsvTokenizer.<init>(CsvTokenizer.java:59)
	at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:246)
	at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
	at org.embulk.spi.util.Executors.process(Executors.java:62)
	at org.embulk.spi.util.Executors.process(Executors.java:38)
	at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:170)
	at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:167)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

I wonder why `getQuoteChar` on CsvParserPlugin returns a `Optional<String>` value.
Do you have any solutions for this probrem?

**Comment by hiroyuki-sato** [comment] 2020-02-25 13:03
Hello, @joker1007 

I'm not familiar `runOutput` method. 
Have you ever try without `out` part?

NOW

```yaml
out:
  type: kafka
  topic: "json-topic"
  serialize_format: json
  brokers:
    - "localhost:9092"
```

Proposed change

```yaml
type: kafka
topic: "json-topic"
serialize_format: json
brokers:
  - "localhost:9092"
```

### Ref

* [
embulk-output-s3_parquet](https://github.com/civitaspo/embulk-output-s3_parquet/blob/develop/src/test/scala/org/embulk/output/s3_parquet/TestS3ParquetOutputPlugin.scala#L57-L66)
* [embulk-output-jdbc](https://github.com/embulk/embulk-output-jdbc/blob/master/ci/travis_mysql.yml)


Those files also may help.

```
rg -l runOutput
embulk-output-s3_parquet/src/test/scala/org/embulk/output/s3_parquet/TestS3ParquetOutputPlugin.scala
embulk-output-cassandra/src/test/java/org/embulk/output/cassandra/TestCassandraOutputPlugin.java
embulk-output-multi/src/test/java/org/embulk/output/multi/TestMultiOutputPlugin.java
embulk-output-jdbc/embulk-output-mysql/src/test/java/org/embulk/output/mysql/AfterLoadTest.java
embulk-output-jdbc/embulk-output-mysql/src/test/java/org/embulk/output/mysql/RetryTest.java
embulk-output-jdbc/embulk-output-mysql/src/test/java/org/embulk/output/mysql/BeforeLoadTest.java
embulk-output-jdbc/embulk-output-mysql/src/test/java/org/embulk/output/mysql/CreateTableTest.java
embulk-output-jdbc/embulk-output-postgresql/src/test/java/org/embulk/output/postgresql/BasicTest.java
embulk-output-jdbc/embulk-output-db2/src/test/java/org/embulk/output/db2/BasicTest.java
embulk-output-jdbc/embulk-output-oracle/src/test/java/org/embulk/output/oracle/BasicTest.java
embulk-output-jdbc/embulk-output-sqlserver/src/test/java/org/embulk/output/sqlserver/BasicTest.java
embulk-output-jdbc/embulk-output-sqlserver/src/test/java/org/embulk/output/sqlserver/NativeTest.java
```

**Comment by joker1007** [comment] 2020-02-25 15:05
@hiroyuki-sato 
Thank you for the comment.

I'm sorry for my explanation.
I've already tried this format.
There are some configurations with `out:` part on https://github.com/joker1007/embulk-output-kafka/commit/4cd289e.
But, that is just base commit.
I fixed the YAML format after https://github.com/joker1007/embulk-output-kafka/commit/4cd289e and executed the test.
Although I did so, the test is failed with such error.

**Comment by hiroyuki-sato** [comment] 2020-02-27 08:29
Hello, @joker1007 

I made [embulk-output-hoge](https://github.com/hiroyuki-sato/embulk-output-hoge) for testing output plugin.
This plugin does nothing, `./gradlew test` execute unit test and build success.
(It call runOutput method)
https://github.com/hiroyuki-sato/embulk-output-hoge/blob/10655d027c69f03fafc1572a76cbb7718763b81a/src/test/java/org/embulk/output/hoge/TestHogeOutputPlugin.java#L33

Could you show me your input CSV data again?

I got the `IllegalArgumentException: tuple must be a pair of column name and type` when I changed to your test data like the following

```
id,int_item,varchar_item
A001,1,a
A002,2,b
A003,3,c
```

It seems that first row require `name:format` column name like 'id:string'
This CSV data passed in my plugin. So, I can't reproduce `ClassCastException` in my environment yet.

```csv
id:string,int_item:long,varchar_item:string
A001,1,a
A002,2,b
A003,3,c
```

**Comment by joker1007** [comment] 2020-02-28 20:36
Input CSV is this.

```
id:string,int_item:long,varchar_item:string
"A001","1","a"
"A002","2","b"
"A003","3","c"
```

**Comment by hiroyuki-sato** [comment] 2020-02-29 05:53
Hello, @joker1007 

Thank you for your reply.

I'm trying to reproduce this Exception in [embulk-output-kafka](https://github.com/hiroyuki-sato/embulk-output-kafka)
https://github.com/hiroyuki-sato/embulk-output-kafka/commit/1cc18e81950700a382fa90a431881831250539d1

I can't reproduce it. I got the following exception instead of that error.

```
org.embulk.config.ConfigException: Attribute type is required but not set
	at org.embulk.config.DataSourceImpl.get(DataSourceImpl.java:67)
	at org.embulk.exec.BulkLoader$ProcessPluginSet.<init>(BulkLoader.java:425)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:502)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
```

## My test environment

* OS: Ubuntu 18.04
* Java: openjdk version "1.8.0_242"


## Additional note

I would like to share my investigation.

A parser in embulk-test use the following configuration.

If input data doesn't match with the configuration, it may raise an exception.

```yaml
parser:
  type: csv
  charset: UTF-8
  newline: LF
  delimiter: ","
  quote: "\""
  escape: "\""
  columns: # use input data header name:type
```

https://github.com/embulk/embulk/blob/75ede58c158ca5220e9b71afa095cae7307b693e/embulk-test/src/main/java/org/embulk/test/TestingEmbulk.java#L452-L459

**Comment by joker1007** [comment] 2020-02-29 17:08
@hiroyuki-sato 

I pushed new branch (https://github.com/joker1007/embulk-output-kafka/tree/testing).
The below process can re-produce `ClassCastException` on the branch.

1. `docker-compose up` launches kafka broker.
1. `docker-compose exec broker kafka-topics --bootstrap-server localhost:9092 --create --topic json-topic --partitions 1 --replication-factor 1`
1. `./gradlew test`

And I have already read the part of TestingEmbulk.
My input CSV seems to follow the parser configuration.

**Comment by hiroyuki-sato** [comment] 2020-03-01 08:05
Hello, @joker1007 

I reproduced your issue in my environment.
It seems that this error relates to `kafka-junit`
(I don't know the reason yet.)



### embulk-output-kafka test

Original code


```
./gradlew test

> Task :test

org.embulk.output.kafka.TestKafkaOutputPlugin > testSimpleJson FAILED
    org.embulk.exec.PartialExecutionException at TestKafkaOutputPlugin.java:24
        Caused by: java.lang.ClassCastException

1 test completed, 1 failed
```

Remove `com.github.charithe:kafka-junit`


```diff
diff --git a/build.gradle b/build.gradle
index bbe2bcd..6476cc7 100644
--- a/build.gradle
+++ b/build.gradle
@@ -37,8 +37,8 @@ dependencies {
     compile("io.confluent:kafka-avro-serializer:5.3.0") {
     }
 
-    testCompile("com.github.charithe:kafka-junit:4.1.6") {
-    }
+//    testCompile("com.github.charithe:kafka-junit:4.1.6") {
+//    }
 }
 
 task classpath(type: Copy, dependsOn: ["jar"]) {
```

test again


```
./gradlew test

> Task :test

org.embulk.output.kafka.TestKafkaOutputPlugin > testSimpleJson FAILED
    org.embulk.exec.PartialExecutionException at TestKafkaOutputPlugin.java:24
        Caused by: org.embulk.config.ConfigException at TestKafkaOutputPlugin.java:24
            Caused by: java.lang.ArrayIndexOutOfBoundsException at TestKafkaOutputPlugin.java:24

1 test completed, 1 failed
```

### embulk-output-hoge

https://github.com/hiroyuki-sato/embulk-output-hoge/commit/16a7676975351dad5bb896f607fd6948a76592d6


original code

```
./gradlew test

BUILD SUCCESSFUL in 5s
4 actionable tasks: 4 up-to-date
```

Add `kafka-junit`

```diff
diff --git a/build.gradle b/build.gradle
index 7ce1918..3c6206d 100644
--- a/build.gradle
+++ b/build.gradle
@@ -49,8 +49,8 @@ dependencies {
         exclude group: "org.slf4j", module: "slf4j-api"
     }
 
-//    testCompile("com.github.charithe:kafka-junit:4.+") {
-//    }
+    testCompile("com.github.charithe:kafka-junit:4.+") {
+    }
 
 
 }
```



```
 ./gradlew test

> Task :test

org.embulk.output.hoge.TestHogeOutputPlugin > testNormalRun FAILED
    org.embulk.exec.PartialExecutionException at TestHogeOutputPlugin.java:35
        Caused by: java.lang.ClassCastException

2 tests completed, 1 failed
```

**Comment by hiroyuki-sato** [comment] 2020-03-02 12:47
Hello, @joker1007 

Could you try the following?
Thanks! @dmikurube [Twitter](https://twitter.com/dmikurube/status/1234453339154214918?s=20)

embulk-output-hoge test passed with `kafka-junit`.
(I can't test embulk-output-kafka now)
https://github.com/hiroyuki-sato/embulk-output-hoge/commit/7cf5ebdb604e2ca69caf45e27ce7db01edb891ef


```
    compile("org.apache.kafka:kafka-clients:2.3.0") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    compile("org.apache.avro:avro:1.9.0") {
        exclude group: "com.fasterxml.jackson.core", module: "jackson-databind"
        exclude group: "com.fasterxml.jackson.core", module: "jackson-annotations"
        exclude group: "com.fasterxml.jackson.core", module: "jackson-core"
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    compile("io.confluent:kafka-avro-serializer:5.3.0") {
        exclude group: "com.fasterxml.jackson.core", module: "jackson-databind"
        exclude group: "com.fasterxml.jackson.core", module: "jackson-annotations"
        exclude group: "com.fasterxml.jackson.core", module: "jackson-core"
        exclude group: "org.slf4j", module: "slf4j-api"
    }

    testCompile("com.github.charithe:kafka-junit:4.+") {
        exclude group: "com.fasterxml.jackson.core"
        exclude group: "com.fasterxml.jackson.module"
        exclude group: "com.fasterxml.jackson.dataformat"
        exclude group: "com.fasterxml.jackson.datatype"
    }

    testCompile "com.fasterxml.jackson.core:jackson-core:2.6.7"
    testCompile "com.fasterxml.jackson.core:jackson-databind:2.6.7"
    testCompile "com.fasterxml.jackson.core:jackson-annotations:2.6.7"
    testCompile "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.6.7"
    testCompile("com.fasterxml.jackson.module:jackson-module-scala_2.12:2.6.7.1") {
        exclude group: "com.fasterxml.jackson.module"
    }
    testCompile "com.fasterxml.jackson.module:jackson-module-paranamer:2.6.7"
    testCompile "com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.6.7"
    testCompile "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.6.7"
```

**Comment by joker1007** [comment] 2020-03-02 12:59
Thank you so much @hiroyuki-sato 
I tried this and reproduced `ArrayIndexOutOfBoundsException`.
As you think, this error is caused by the mismatch of the version of jackson probably.
The problem of jackson version is very annoying :disappointed:

**Comment by hiroyuki-sato** [comment] 2020-03-02 14:52
Hello, @joker1007 

I succeeded the embulk-output-kafka test with the above patch.

 https://github.com/hiroyuki-sato/embulk-output-kafka/commit/0e14aef6ce2d36aa6f0d59b43790c6929e382ae4

The core-team working for resolving the dependency hell.
I hope the problem will solve in the near future. :smiley:

**Comment by joker1007** [comment] 2020-03-03 11:24
@hiroyuki-sato 
Thank you so much for your support!!
I tried to exclude jackson modules and I succeeded to run tests too. :+1: 
I also hope such a problem is solved.

**Closed** 2020-03-03 11:25 UTC
