### ISSUE TITLE
-b flag broken in release 0.8.24

### ISSUE THREAD

**Issue by bcipolli** [embulk/embulk#680] opened 2017-06-15 18:34 UTC
When running `embulk` with `-b` flag, the following error occurs:
`NameError: undefined local variable or method `bundle_path index' for main:Object`

I believe this is a bug (undefined variable), introduced here:

https://github.com/embulk/embulk/commit/09cd22e929c9652bf82854cd23da99fd4aa74c62#diff-b63a1c764c39ff316cef4fd26d70b97aR6

**Comment by dmikurube** [comment] 2017-06-16 00:15
Ah, sorry, I overlooked this issue. Taking a look.

Can you share your environment (OS, etc), and the command-line you ran?

**Comment by dmikurube** [comment] 2017-06-16 00:19
Ah, but `bundle_path_index` is definitely a bug... Okay, will fix. Thanks for reporting.

**Comment by dmikurube** [comment] 2017-06-16 00:26
Hmm? But that file (commit) is already fixed in #604. The current `embulk_bundle.rb` is https://github.com/embulk/embulk/blob/6155ec0901be467d2525768a45121549f500b09a/lib/embulk/command/embulk_bundle.rb.

Again, can you share your environment (OS, etc), and the command-line you ran? @bcipolli

**Comment by dmikurube** [comment] 2017-06-16 00:28
Sorry, I's confused. Removed a comment. 09cd22e is fixed, but the line is alive finally. Will fix.

**Comment by dmikurube** [comment] 2017-06-16 07:11
Being fixed in #681, and releasing v0.8.25 with the fix.

**Closed** 2017-06-16 07:17 UTC

**Comment by dmikurube** [comment] 2017-06-16 07:50
@bcipolli Released v0.8.25. This issue should be fixed there -- can you try, and reopen this if the problem is still there?
