### ISSUE TITLE
Can not find InputPlugin 'postgresql' error

### ISSUE THREAD

**Issue by gccj** [embulk/embulk#1001] opened 2018-04-08 08:33 UTC
Hello, members.
I got the following errors when i running embulk tasks.
 > org.embulk.config.ConfigException: InputPlugin 'postgresql' is not found.

The embulk bundle install was successful.
Some task was run successfully, some was got this error.

#### Environment
 - Digdag 0.9.24
 - Embulk 0.9.5
 - embulk-input-postgresql 0.9.1

#### Logs
```
2018-04-08 08:00:00.368 +0000 [INFO] (main): Started Embulk v0.9.5
2018-04-08 08:00:00.539 +0000 [INFO] (0018:task-0000): > 0.36 seconds
2018-04-08 08:00:00.549 +0000 [INFO] (0018:task-0000): Fetched 500 rows.
2018-04-08 08:00:00.555 +0000 [INFO] (0018:task-0000): Fetched 1,000 rows.
2018-04-08 08:00:00.578 +0000 [INFO] (0018:task-0000): Fetched 2,000 rows.
2018-04-08 08:00:00.645 +0000 [INFO] (0018:task-0000): Fetched 4,000 rows.
2018-04-08 08:00:00.745 +0000 [INFO] (0018:task-0000): Fetched 8,000 rows.
2018-04-08 08:00:00.777 +0000 [INFO] (0018:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2018-04-08 08:00:00.965 +0000 [INFO] (0001:transaction): BUNDLE_GEMFILE is being set: "/home/xxxx/./Gemfile"
2018-04-08 08:00:00.966 +0000 [INFO] (0001:transaction): Gem's home and path are being cleared.
org.embulk.config.ConfigException: InputPlugin 'postgresql' is not found.
java.lang.NullPointerException: Inflater has been closed
at org.embulk.plugin.PluginManager.buildPluginNotFoundException(PluginManager.java:78)
at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:64)
at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:31)
at org.embulk.spi.ExecSession.newPlugin(ExecSession.java:147)
at org.embulk.spi.Exec.newPlugin(Exec.java:63)
at org.embulk.exec.BulkLoader$ProcessPluginSet.<init>(BulkLoader.java:409)
at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:484)
at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
at org.embulk.spi.Exec.doWith(Exec.java:22)
at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:162)
at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:436)
at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
at org.embulk.cli.Main.main(Main.java:26)
Suppressed: org.embulk.plugin.PluginSourceNotMatchException
at org.embulk.plugin.InjectedPluginSource.newPlugin(InjectedPluginSource.java:53)
at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:52)
... 16 more
Suppressed: org.embulk.plugin.PluginSourceNotMatchException
at org.embulk.plugin.maven.MavenPluginSource.newPlugin(MavenPluginSource.java:65)
at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:52)
... 16 more
Suppressed: org.embulk.plugin.PluginSourceNotMatchException: org.jruby.embed.EvalFailedException: java.lang.NullPointerException: Inflater has been closed
at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:63)
at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:59)
... 16 more
Caused by: org.jruby.embed.EvalFailedException: java.lang.NullPointerException: Inflater has been closed
at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:137)
at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1300)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.embulk.jruby.ScriptingContainerDelegateImpl.runScriptlet(ScriptingContainerDelegateImpl.java:764)
at org.embulk.jruby.JRubyInitializer.setBundlerPluginSourceDirectory(JRubyInitializer.java:222)
at org.embulk.jruby.JRubyInitializer.initialize(JRubyInitializer.java:109)
at org.embulk.jruby.LazyScriptingContainerDelegate.getInitialized(LazyScriptingContainerDelegate.java:206)
at org.embulk.jruby.LazyScriptingContainerDelegate.runScriptlet(LazyScriptingContainerDelegate.java:186)
at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:60)
... 17 more
Caused by: java.lang.NullPointerException: Inflater has been closed
at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
at java.util.zip.Inflater.inflate(Inflater.java:257)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
at org.jruby.util.io.PosixShim.read(PosixShim.java:157)
at org.jruby.util.io.OpenFile$2.run(OpenFile.java:1314)
at org.jruby.util.io.OpenFile$2.run(OpenFile.java:1304)
at org.jruby.RubyThread.executeTask(RubyThread.java:1486)
at org.jruby.util.io.OpenFile.readInternal(OpenFile.java:1377)
at org.jruby.util.io.OpenFile.ioBufread(OpenFile.java:1714)
at org.jruby.util.io.OpenFile.bufreadCall(OpenFile.java:1754)
at org.jruby.util.io.OpenFile.fread(OpenFile.java:1771)
at org.jruby.util.io.OpenFile.readAll(OpenFile.java:1677)
at org.jruby.RubyIO.read(RubyIO.java:3082)
at org.jruby.RubyIO.read(RubyIO.java:3066)
at org.jruby.RubyIO.read19(RubyIO.java:3680)
at org.jruby.RubyIO$INVOKER$s$0$3$read19.call(RubyIO$INVOKER$s$0$3$read19.gen)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:127)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:344)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
at org.jruby.Ruby.runInterpreter(Ruby.java:848)
at org.jruby.Ruby.runInterpreter(Ruby.java:852)
at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:118)
... 29 more
Error: InputPlugin 'postgresql' is not found.
java.lang.NullPointerException: Inflater has been closed
2018-04-08 08:00:01.124 +0000 [INFO] (0018:task-0000): > 0.35 seconds
2018-04-08 08:00:01.128 +0000 [INFO] (0018:task-0000): Fetched 500 rows.

```

**Comment by hiroyuki-sato** [comment] 2018-04-08 09:35
Hello, @gccj 

Hmm It's strange. I'm using digdag and embulk in similar environment.

* How do you run embulk and digdag? Which mode( server or local) are you use in Digdag?
* Can you try it without digdag?
* Can you show me your configuration?

**Comment by hiroyuki-sato** [comment] 2018-04-09 00:32
This is an [embulk input sample with digdag](https://github.com/hiroyuki-sato/embulk-support/blob/master/core_1001_plugin_not_found/00README.md).

**Comment by gccj** [comment] 2018-04-09 02:42
Hi @hiroyuki-sato 

> How do you run embulk and digdag? Which mode( server or local) are you use in Digdag?

**A:**
Yes I'm using digdag.
All the stuff are running on AWS ECS with Digdag scheduler mode.
```
CMD ["java", "-jar", "/usr/local/bin/digdag", "scheduler", "-b", "0.0.0.0", "-P", "config.yml", "--access-log", ".digdag/logs/accesslogs", "--task-log", ".digdag/logs/tasklogs", "--max-task-threads", "4"]
```
> Can you show me your configuration?

**A:**
Embulk configuration:
```
in:
  type: postgresql
  host: {{ env.EMBULK_INPUT_DB_HOST }}
  user: {{ env.EMBULK_INPUT_DB_USER }}
  password: {{ env.EMBULK_INPUT_DB_PASS }}
  database: {{ env.EMBULK_INPUT_DB_DATABASE }}
  table: {{ env.TABLE }}
  select: '*'
  default_timezone: 'Asia/Tokyo'
  ssl: true

{% if env.NEED_SET_FILTERS_TABLES contains env.TABLE %}
{% assign filter_file = 'commons/filters/' | append: env.TABLE %}
{% include filter_file %}
{% endif %}

out:
  type: postgresql
  host: {{ env.EMBULK_OUTPUT_DB_HOST }}
  user: {{ env.EMBULK_OUTPUT_DB_USER }}
  password: {{ env.EMBULK_OUTPUT_DB_PASS }}
  database: {{ env.EMBULK_OUTPUT_DB_DATABASE }}
  table: {{ env.TABLE }}
  mode: merge
  default_timezone: 'Asia/Tokyo'
  ssl: true
{% if env.NEED_SET_MERGE_KEYS_TABLES contains env.TABLE %}
{% assign merge_keys_file = 'commons/merge_keys/' | append: env.TABLE %}
{% include merge_keys_file %}
{% endif %}
{% if env.NEED_SET_COLUMN_OPTIONS_TABLES contains env.TABLE %}
{% assign column_options_file = 'commons/column_options/' | append: env.TABLE %}
{% include column_options_file %}
{% endif %}
```
And this is how i call it:
```
# main dig file

timezone: Asia/Tokyo

schedule:
  daily>: 00:00:00

_export:
  ...

+fetch_table_list:
 ...

+fetch_sequence_list:
  ...

+generate_filter_files:
  ...

+generate_merge_keys_files:
 ...

+generate_column_options_files:
  ...

+stash_all_fk_constraint:
  ...

+sync_tables:
  for_each>:
    TABLE: ${TABLE_LIST}
  _parallel: true
  _do:
    call>: sync_table.dig
  _check:
    slack>: tasks/slack/success-template.yml
  _error:
    call>: clean_up.dig

# Clean Up
+clean_up:
  call>: clean_up.dig

```
```
# sync_table.dig

+sync_table_embulk:
  _retry: 3
  sh>: /usr/local/bin/embulk run -b ./ tasks/embulk/table_to_table.yml.liquid
  _error:
    slack>: tasks/slack/failed-template.yml
```

> Can you try it without digdag?

As you can see the embulk task was require other tasks like ```fetch_table_list```, So it was difficult ```try it without digdag```.

**A:**
With digdag if I retry the failed tasks due to ```InputPlugin 'postgresql' is not found.``` , it will be run successful.

**Comment by sakama** [comment] 2018-04-09 02:58
@gccj Have you formerly used different version of Embulk?
If yes, you may be able to solve your problem by once remove `~/.embulk` and re-install Embulk.

Additionally, as @hiroyuki-sato mentioned at above, Try with only Embulk with simple configuration is helpful to detect the cause.
```yaml
in:
  type: postgresql
  host: {{ env.EMBULK_INPUT_DB_HOST }}
  user: {{ env.EMBULK_INPUT_DB_USER }}
  password: {{ env.EMBULK_INPUT_DB_PASS }}
  database: {{ env.EMBULK_INPUT_DB_DATABASE }}
  table: {{ env.TABLE }}
  select: '*'
  default_timezone: 'Asia/Tokyo'
  ssl: true
type: stdout
```

**Comment by hiroyuki-sato** [comment] 2018-04-09 03:06
Hello, @gccj 

If you installed embulk plugin outside of the digdag project,
Can you try to change to absolute path (e.g.`-b /path/do/bundledir`) instead of relative path (`-b .`) in you `dig` file?
(e.g. `/usr/local/bin/embulk run -b ./ tasks/embulk/table_to_table.yml.liquid`)

Digdag changes working directory for make sandbox environment. I suspect the `-b .` option reference another directory.

**Comment by gccj** [comment] 2018-04-09 03:16
@hiroyuki-sato thank you for reply.

I exec ```embulk bundle --path vendor/bundle``` under the Digdag project directory.
So ```.``` is ```/path/to/bundledir```.
I will try change to absolute path of  ```.```  instead of relative path ``` .```

**Comment by gccj** [comment] 2018-04-09 03:25
@hiroyuki-sato 
Question:
If ```-b .``` option reference another directory, all of the embulk task will got failure, right?

**Comment by hiroyuki-sato** [comment] 2018-04-09 03:27
Hello @gccj 

If you installed embulk plugins into digdag project,
You can't change absolute path. Because digdag always change working directory.
If your project structure like the below, Can you try `-b vendor/bundle`?


```
digdag_project_root
|-- xxx.dig
+-- vender
       +-- bundle
```

> If -b . option reference another directory, all of the embulk task will got failure, right?

YES

**Comment by gccj** [comment] 2018-04-09 03:36
Hi @hiroyuki-sato

> If your project structure like the below, Can you try -b vendor/bundle?

Thank you! I will try it, and report the result tomorrow.

> If -b . option reference another directory, all of the embulk task will got failure, right?
>YES

With the present condition some embulk task(```sync_table_embulk```) run successfully, some don't.

**Comment by hiroyuki-sato** [comment] 2018-04-09 04:30
I recreate [an example](https://github.com/hiroyuki-sato/embulk-support/blob/master/core_1001_plugin_not_found/00README.md)

The option `-b vendor/bundle` worked well in my environment.

> With the present condition some embulk task(sync_table_embulk) run successfully, some don't.

I can't understand this comment. It seems that Your embulk config always fails to load PostgreSQL input plugin. So I think your task always failed. Please minimize the problem.

**Comment by gccj** [comment] 2018-04-09 07:27
Hello @hiroyuki-sato  

> I can't understand this comment. It seems that Your embulk config always fails to load PostgreSQL input plugin. So I think your task always failed. Please minimize the problem.

Sorry for the ambiguous explanation.
It means embulk config fails to load PostgreSQL input plugin sometimes(not always).
So some sub task(embulk task) failed sometimes.
e.g.
```
+sync_tables:
  for_each>:
    TABLE: [A, B, C, D]
  _parallel: true
  _do:
    call>: sync_table.dig
  _check:
    slack>: tasks/slack/success-template.yml
  _error:
    call>: clean_up.dig
```
```
# sync_table.dig

+sync_table_embulk:
  _retry: 3
  sh>: /usr/local/bin/embulk run -b ./ tasks/embulk/table_to_table.yml.liquid
  _error:
    slack>: tasks/slack/failed-template.yml
```

Success:
```sync_tables^sub+for-0=TABLE=0=A^sub+sync_table_embulk```
```sync_tables^sub+for-0=TABLE=1=B^sub+sync_table_embulk``` 
```sync_tables^sub+for-0=TABLE=3=D^sub+sync_table_embulk```

Failure:
```sync_tables^sub+for-0=TABLE=2=C^sub+sync_table_embulk``` 

And if I rerun ```sync_tables^sub+for-0=TABLE=2=C^sub+sync_table_embulk```  -> Success


- Logs
```
2018-04-08 08:06:36.166 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "public”.”xxx_00000162a44ad72e_embulk001"
2018-04-08 08:06:36.168 +0000 [INFO] (0001:transaction): > 0.00 seconds
2018-04-08 08:06:36.170 +0000 [INFO] (main): Committed.
2018-04-08 08:06:36.171 +0000 [INFO] (main): Next config diff: {"in":{},"out":{}}    
#### Success ####
#### Success ####
2018-04-08 08:06:22.527 +0000 [INFO] (0043@[0:default]+sync_db_data+sync_tables^sub+for-0=TABLE=55=xxxxx_^sub+sync_table_embulk) io.digdag.core.agent.OperatorManager: sh>: /usr/local/bin/embulk run -b ./ tasks/embulk/table_to_table.yml.liquid                                                                                                                                                                                                                              
2018-04-08 08:06:23.299 +0000: Embulk v0.9.5
2018-04-08 08:06:38.191 +0000 [INFO] (main): Started Embulk v0.9.5
2018-04-08 08:06:38.963 +0000 [INFO] (0001:transaction): BUNDLE_GEMFILE is being set: "/home/xxxxxx/./Gemfile"
2018-04-08 08:06:38.981 +0000 [INFO] (0001:transaction): Gem's home and path are being cleared.
2018-04-08 08:06:42.828 +0000 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.9.1)
2018-04-08 08:06:42.955 +0000 [INFO] (0001:transaction): Loaded plugin embulk-output-postgresql (0.8.0)
2018-04-08 08:06:43.149 +0000 [INFO] (0001:transaction): JDBC Driver = /home/xxxxxx/vendor/bundle/jruby/2.3.0/gems/embulk-input-postgresql-0.9.1/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2018-04-08 08:06:43.185 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql:xxxxxx
2018-04-08 08:06:45.066 +0000 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2018-04-08 08:06:45.279 +0000 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2018-04-08 08:06:46.128 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=4 / output tasks 2 = input tasks 1 * 2
2018-04-08 08:06:46.221 +0000 [INFO] (0001:transaction): JDBC Driver = /home/xxxxxx/vendor/bundle/jruby/2.3.0/gems/embulk-output-postgresql-0.8.0/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2018-04-08 08:06:46.229 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql:xxxxxx

……

2018-04-08 08:06:50.408 +0000 [INFO] (main): Committed.
2018-04-08 08:06:50.408 +0000 [INFO] (main): Next config diff: {"in":{},"out":{}}
#### Success ####

#### Failure ####
2018-04-08 08:06:39.908 +0000 [INFO] (0048@[0:default]+sync_db_data+sync_tables^sub+for-0=TABLE=57=xxxxxxx^sub+sync_table_embulk) io.digdag.core.agent.OperatorManager: sh>: /usr/local/bin/embulk run -b ./ tasks/embulk/table_to_table.yml.liquid
2018-04-08 08:06:40.773 +0000: Embulk v0.9.5
2018-04-08 08:06:56.597 +0000 [INFO] (main): Started Embulk v0.9.5
2018-04-08 08:06:57.710 +0000 [INFO] (0001:transaction): BUNDLE_GEMFILE is being set: "/home/xxxxxx/./Gemfile"
2018-04-08 08:06:57.721 +0000 [INFO] (0001:transaction): Gem's home and path are being cleared.

……

org.embulk.config.ConfigException: InputPlugin 'postgresql' is not found.

……

Error: InputPlugin 'postgresql' is not found.

……

2018-04-08 08:06:57.928 +0000 [ERROR] (0048@[0:default]+sync_db_data+sync_tables^sub+for-0=TABLE=57=xxxxxxx^sub+sync_table_embulk) io.digdag.core.agent.OperatorManager: Task failed, retrying

……

#### Failure ####

#### Success ####
2018-04-08 08:06:43.931 +0000 [INFO] (0046@[0:default]+sync_db_data+sync_tables^sub+for-0=TABLE=58=xxxxxxx^sub+sync_table_embulk) io.digdag.core.agent.OperatorManager: sh>: /usr/local/bin/embulk run -b ./ tasks/embulk/table_to_table.yml.liquid
2018-04-08 08:06:44.498 +0000: Embulk v0.9.5
2018-04-08 08:06:59.869 +0000 [INFO] (main): Started Embulk v0.9.5
2018-04-08 08:07:01.166 +0000 [INFO] (0001:transaction): BUNDLE_GEMFILE is being set: "/home/xxxxxx/./Gemfile"
2018-04-08 08:07:01.167 +0000 [INFO] (0001:transaction): Gem's home and path are being cleared.
2018-04-08 08:07:05.355 +0000 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.9.1)
2018-04-08 08:07:05.476 +0000 [INFO] (0001:transaction): Loaded plugin embulk-output-postgresql (0.8.0)
2018-04-08 08:07:05.667 +0000 [INFO] (0001:transaction): JDBC Driver = /home/xxxxxx/vendor/bundle/jruby/2.3.0/gems/embulk-input-postgresql-0.9.1/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2018-04-08 08:07:05.678 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql://xxxxxx
2018-04-08 08:07:07.486 +0000 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2018-04-08 08:07:07.703 +0000 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2018-04-08 08:07:08.619 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=4 / output tasks 2 = input tasks 1 * 2
2018-04-08 08:07:08.696 +0000 [INFO] (0001:transaction): JDBC Driver = /home/xxxxxx/vendor/bundle/jruby/2.3.0/gems/embulk-output-postgresql-0.8.0/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2018-04-08 08:07:08.706 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql://xxxxxx
2018-04-08 08:07:08.987 +0000 [INFO] (0001:transaction): SQL: SET search_path TO "public"

……

2018-04-08 08:07:13.379 +0000 [INFO] (main): Committed.
2018-04-08 08:07:13.379 +0000 [INFO] (main): Next config diff: {"in":{},"out":{}}
……

#### Success ####
```


> Ca you double check ~/.embulk directory?

Ok, I will do it.
_All the things was running on docker container, so it only one version of embulk in it._

**Comment by hiroyuki-sato** [comment] 2018-04-09 08:59
Hello, @gccj 

Can you minimize your problem?
If we can't reproduce your issue in our environment, we can't fix it.

I tried to reproduce your issue(parallel run embulk) in my environment, It seems work well.
https://github.com/hiroyuki-sato/embulk-support/blob/master/core_1001_plugin_not_found/00README.md#digdag-scheduler-in-pararallel

* An error occurred on a specific or random table?
* How about without docker?
* How did you run digdag in docker container?


My environment
* macOS 10.13.4
* Embulk 0.9.5
* embulk-input-postgresql: 0.9.1
* Digdag 0.9.5
* PostgreSQL: 9.6

**Comment by dmikurube** [comment] 2018-09-25 06:56
@gccj Has your problem been resolved?

I'm closing this issue for the time being. If you still see a problem, please reopen this issue.

**Closed by dmikurube** 2018-09-25 06:56 UTC
